### ISSUE TITLE
服务启动 问题

### ISSUE THREAD

**Issue by token01** [infinitbyte/gopa#17]
D:\go\src\github.com\infinitbyte\gopa>go build -o bin/gopa.exe
# github.com/infinitbyte/gopa/vendor/github.com/jbowles/nlpt-detect/vendor/github.com/jbowles/nlpt-cld2
C:\WINDOWS\TEMP\cgo-gcc-input-925127079.c:0: sorry, unimplemented: 64-bit mode not compiled in
# github.com/infinitbyte/gopa/vendor/github.com/mattn/go-sqlite3
cc1.exe: error: unrecognized command line option "-fno-stack-protector"
C:\WINDOWS\TEMP\cgo-gcc-input-631019887.c:0: sorry, unimplemented: 64-bit mode not compiled in

**Comment by medcl** [comment]
是安装这个说明来执行的么？
https://github.com/infinitbyte/gopa/wiki/How-to-build-GOPA-on-windows

**Comment by token01** [comment]
是按照这个执行的 也安装的依赖包  但是还是不行

**Comment by liaosy21** [comment]
@token01 我就是按照这个文档（https://github.com/infinitbyte/gopa/wiki/How-to-build-GOPA-on-windows） 来操作的，能正常启动并运行。我的是windows10环境，建议你按照文档说明步骤再重新梳理一遍，注意GOPATH要设置正确。
