### ISSUE TITLE
mac 安装版本不兼容？

### ISSUE THREAD

**Issue by token01** [infinitbyte/gopa#18]
➜  github.com go version
go version go1.9.2 darwin/amd64
➜  github.com go get github.com/infinitbyte/gopa
# github.com/infinitbyte/gopa/core/env
../../../../go/src/github.com/infinitbyte/gopa/core/env/version.go:32:9: undefined: lastCommitLog
../../../../go/src/github.com/infinitbyte/gopa/core/env/version.go:33:38: undefined: lastCommitLog
../../../../go/src/github.com/infinitbyte/gopa/core/env/version.go:41:9: undefined: lastCommitLog
../../../../go/src/github.com/infinitbyte/gopa/core/env/version.go:46:9: undefined: buildDate

**Comment by token01** [comment]
ee

**Comment by medcl** [comment]
请使用 make 命令来编译，有两个文件是动态生成的。

**Comment by medcl** [comment]
@token01 新的代码支持 go get 来进行安装了
