### ISSUE TITLE
make build error

### ISSUE THREAD

**Issue by yyw794** [infinitbyte/gopa#20]
as your README.md instruction, after 
```
make build
```
error:
`/bin/bash: esc: command not found`

**Comment by medcl** [comment]
Please read the docs:
https://github.com/infinitbyte/gopa/wiki/How-to-build-GOPA-on-windows
https://github.com/infinitbyte/gopa/wiki/How-to-build-GOPA-on-macOS
make sure you follow these instruction and set the right GO related environment variable.
