### ISSUE TITLE
ego: command not found

### ISSUE THREAD

**Issue by tiod** [infinitbyte/gopa#21]
[df@gopa gopa-0.9.0]$ cat /etc/redhat-release 
CentOS Linux release 7.4.1708 (Core) 

[df@gopa gopa-0.9.0]$ make build
echo -e "package env\nconst lastCommitLog  =\""`git log -1 --pretty=format:"%h, %ad, %an, %s"` "\"\nconst buildDate  =\"`date`\"" > core/env/commit_log.go
fatal: Not a git repository (or any of the parent directories): .git
GO15VENDOREXPERIMENT="1" go get github.com/infinitbyte/esc
(cd static&& esc -ignore="static.go|build_static.sh|.DS_Store" -o static.go -pkg static ../static )
GO15VENDOREXPERIMENT="1" go get github.com/infinitbyte/ego/cmd/ego
cd modules/ui/ && ego
/bin/bash: ego: command not found
make: *** [update-template-ui] Error 127

**Comment by medcl** [comment]
GO的环境变量设置对了么?以下供参考
```
export GOROOT=/usr/local/Cellar/go/1.9/libexec
export PATH=$PATH:$GOROOT/bin
export GOPATH=$HOME/go
export PATH="$GOPATH/bin:$PATH:/usr/bin/python"
```
