### ISSUE TITLE
Run gopa on windows

### ISSUE THREAD

**Issue by denghc0607** [infinitbyte/gopa#22]
![82ded5df-081a-45cf-ac44-5abd1245845d](https://user-images.githubusercontent.com/28770147/35313069-64864096-00f9-11e8-9b45-4838e23d67de.png)

help! help! help!  thanks！

**Comment by denghc0607** [comment]
这是配置文件更改的地方：
![20adeade-0aea-4fd5-b83c-50058244124c](https://user-images.githubusercontent.com/28770147/35315820-79b322a8-0109-11e8-929e-84023ff1a026.png)

**Comment by medcl** [comment]
修改成：
![image](https://user-images.githubusercontent.com/64487/35316497-e3307958-010c-11e8-86c1-176d225da228.png)

**Comment by denghc0607** [comment]
感谢！！！ 可以运行了。但是会有个警告：
![82ded5df-081a-45cf-ac44-5abd1245845d](https://user-images.githubusercontent.com/28770147/35322723-391e4c50-0126-11e8-9d5b-a74a27377bfc.png)

而且我访问网址：http://127.0.0.1:9001/admin/console/  后是这个样子，没有地方添加网址：
![b5b05385-bdb8-44e1-9c6c-27a92da59103](https://user-images.githubusercontent.com/28770147/35322816-8a98198a-0126-11e8-9571-6da028a577fe.png)

**Comment by medcl** [comment]
这个是后台的身份认证，可以用你的 github 账号登陆进去，
可以修改配置节点，关闭
```
- name: web
  enabled: true
  auth:
    enabled:  false
```

**Comment by medcl** [comment]
警告不用管，windows 暂时不支持多实例的检测

**Comment by denghc0607** [comment]
@medcl 明白了，多谢！！！ 
![](https://assets-cdn.github.com/images/icons/emoji/unicode/1f44d.png)
![](https://assets-cdn.github.com/images/icons/emoji/unicode/1f604.png)
