### ISSUE TITLE
make issue

### ISSUE THREAD

**Issue by haoglehaogle** [infinitbyte/gopa#25]
hello,
When I build from source, I get follow error:

_**
make build
building GOPA 0.11.0_SNAPSHOT
generate static files
/bin/bash: esc: command not found
Makefile:115: recipe for target 'update-ui' failed
make: *** [update-ui] Error 127
**_

**Comment by igofreely** [comment]
I got the same problem when "make build"
How to get the esc command by  https://github.com/infinitbyte/esc?
By the way,where is the "build.bat" for windows compile gone?

**Comment by medcl** [comment]
regarding `ego` or `esc`  not found, please make sure your config the PATH, check out this issue,
https://github.com/infinitbyte/gopa/issues/21

**Comment by medcl** [comment]
regarding the build.bat, I removed it from the source, you can use a standard command `go build` to build the binary. can you give a try?

**Comment by medcl** [comment]
Fixed with https://github.com/infinitbyte/gopa/commit/d9f3fc1816f89f2847307ed0eebaa80a2652a459
