### ISSUE TITLE
when click admin->task issues

### ISSUE THREAD

**Issue by haoglehaogle** [infinitbyte/gopa#30]
Hello,
gopa work well after I compile it, but I get following error information when I enter admin, and click task.

2018/06/19 10:15:24 http: panic serving 127.0.0.1:44118: not implemented yet
goroutine 444 [running]:
net/http.(*conn).serve.func1(0xc4201f48c0)
	/usr/lib/go-1.10/src/net/http/server.go:1726 +0xd0
panic(0xc189e0, 0xc4202ad2c0)
	/usr/lib/go-1.10/src/runtime/panic.go:502 +0x229
github.com/infinitbyte/framework/modules/persist/elastic.ElasticORM.GroupBy(0xc42000e390, 0xc8c080, 0xc420208000, 0xc9ef5e, 0x4, 0xc9ef5e, 0x4, 0x0, 0x0, 0x0, ...)
	/home/haogle/go/src/github.com/infinitbyte/framework/modules/persist/elastic/elasticsearch.go:154 +0x57
github.com/infinitbyte/framework/core/persist.GroupBy(0xc8c080, 0xc420208000, 0xc9ef5e, 0x4, 0xc9ef5e, 0x4, 0x0, 0x0, 0x0, 0x0, ...)
	/home/haogle/go/src/github.com/infinitbyte/framework/core/persist/orm.go:194 +0xbb
github.com/infinitbyte/gopa/model.GetHostStatus(0xffffffffffffffff, 0x14, 0x0, 0x0)
	/home/haogle/go/src/github.com/infinitbyte/gopa/model/task.go:208 +0x1f6
github.com/infinitbyte/gopa/ui.AdminUI.TasksPageAction(0xc420320000, 0xe59b80, 0xc4202202a0, 0xc4201aae00, 0x0, 0x0, 0x0)
	/home/haogle/go/src/github.com/infinitbyte/gopa/ui/handler.go:28 +0x20d
github.com/infinitbyte/gopa/ui.(AdminUI).TasksPageAction-fm(0xe59b80, 0xc4202202a0, 0xc4201aae00, 0x0, 0x0, 0x0)
	/home/haogle/go/src/github.com/infinitbyte/gopa/ui/init.go:55 +0x6c
github.com/infinitbyte/framework/core/api.NeedPermission.func1(0xe59b80, 0xc4202202a0, 0xc4201aae00, 0x0, 0x0, 0x0)
	/home/haogle/go/src/github.com/infinitbyte/framework/core/api/handler.go:270 +0x7c
github.com/infinitbyte/framework/core/api/router.(*Router).ServeHTTP(0xc4202b7600, 0xe59b80, 0xc4202202a0, 0xc4201aae00)
	/home/haogle/go/src/github.com/infinitbyte/framework/core/api/router/router.go:337 +0x741
github.com/gorilla/context.ClearHandler.func1(0xe59b80, 0xc4202202a0, 0xc4201aae00)
	/home/haogle/git/gopa/vendor/src/github.com/gorilla/context/context.go:141 +0x8b
net/http.HandlerFunc.ServeHTTP(0xc4202f1a80, 0xe59b80, 0xc4202202a0, 0xc4201aae00)
	/usr/lib/go-1.10/src/net/http/server.go:1947 +0x44
net/http.serverHandler.ServeHTTP(0xc4202eeea0, 0xe59b80, 0xc4202202a0, 0xc4201aae00)
	/usr/lib/go-1.10/src/net/http/server.go:2694 +0xbc
net/http.(*conn).serve(0xc4201f48c0, 0xe5a980, 0xc4200bdf00)
	/usr/lib/go-1.10/src/net/http/server.go:1830 +0x651
created by net/http.(*Server).Serve
	/usr/lib/go-1.10/src/net/http/server.go:2795 +0x27b

**Comment by medcl** [comment]
hey, the master code is still under development, and i just moved the default persist engine to es from sqlite, but es is not full supported yet. hand on.
