### ISSUE TITLE
How to run gopa via go run 

### ISSUE THREAD

**Issue by xiaomaijiang** [infinitbyte/gopa#31]
`make build` runs well,but when I use go run build,i got follow errors

`
# github.com/infinitbyte/framework/modules/storage/boltdb
../../../../../../gopath/src/github.com/infinitbyte/framework/modules/storage/boltdb/boltdb.go:67:17: cannot use func literal (type func(*"github.com/boltdb/bolt".Tx) error) as type func(*"github.com/coreos/bbolt".Tx) error in argument to db.Bolt.Update
../../../../../../gopath/src/github.com/infinitbyte/framework/modules/storage/boltdb/boltdb.go:90:51: cannot use boltDb (type *"github.com/boltdb/bolt".DB) as type *"github.com/coreos/bbolt".DB in argument to storm.UseDB
../../../../../../gopath/src/github.com/infinitbyte/framework/modules/storage/boltdb/boltdb.go:92:85: cannot use "github.com/boltdb/bolt".Options literal (type *"github.com/boltdb/bolt".Options) as type *"github.com/coreos/bbolt".Options in argument to storm.BoltOptions
../../../../../../gopath/src/github.com/infinitbyte/framework/modules/storage/boltdb/boltdb.go:138:15: cannot use func literal (type func(*"github.com/boltdb/bolt".Tx) error) as type func(*"github.com/coreos/bbolt".Tx) error in argument to db.Bolt.View
../../../../../../gopath/src/github.com/infinitbyte/framework/modules/storage/boltdb/boltdb.go:162:17: cannot use func literal (type func(*"github.com/boltdb/bolt".Tx) error) as type func(*"github.com/coreos/bbolt".Tx) error in argument to db.Bolt.Update
../../../../../../gopath/src/github.com/infinitbyte/framework/modules/storage/boltdb/boltdb.go:171:17: cannot use func literal (type func(*"github.com/boltdb/bolt".Tx) error) as type func(*"github.com/coreos/bbolt".Tx) error in argument to db.Bolt.Update
../../../../../../gopath/src/github.com/infinitbyte/framework/modules/storage/boltdb/boltdb.go:180:17: cannot use func literal (type func(*"github.com/boltdb/bolt".Tx) error) as type func(*"github.com/coreos/bbolt".Tx) error in argument to db.Bolt.Update
../../../../../../gopath/src/github.com/infinitbyte/framework/modules/storage/boltdb/boltdb.go:189:22: cannot use func literal (type func(*"github.com/boltdb/bolt".Tx) error) as type func(*"github.com/coreos/bbolt".Tx) error in argument to db.Bolt.View
# github.com/infinitbyte/framework/modules/cluster/discovery/raft
../../../../../../gopath/src/github.com/infinitbyte/framework/modules/cluster/discovery/raft/raft.go:106:19: s.raft.Peers undefined (type *raft.Raft has no field or method Peers)
../../../../../../gopath/src/github.com/infinitbyte/framework/modules/cluster/discovery/raft/raft.go:132:9: config.EnableSingleNode undefined (type *raft.Config has no field or method EnableSingleNode)
../../../../../../gopath/src/github.com/infinitbyte/framework/modules/cluster/discovery/raft/raft.go:133:9: config.DisableBootstrapAfterElect undefined (type *raft.Config has no field or method DisableBootstrapAfterElect)
../../../../../../gopath/src/github.com/infinitbyte/framework/modules/cluster/discovery/raft/raft.go:151:16: undefined: raft.StaticPeers
../../../../../../gopath/src/github.com/infinitbyte/framework/modules/cluster/discovery/raft/raft.go:166:25: too many arguments in call to raft.NewRaft
../../../../../../gopath/src/github.com/infinitbyte/framework/modules/cluster/discovery/raft/raft.go:275:21: cannot use addr (type string) as type raft.ServerAddress in argument to s.raft.AddPeer
`

MyEnviroments:

OS:OSX
GoVersion:go version go1.10.1 darwin/amd64
Version of GOPA:master

**Comment by medcl** [comment]
check your code location, should be placed to `~/go/src/github/infinitbyte/gopa`

**Comment by xiaomaijiang** [comment]
I placed the source code to this location,but still has error..

`
../framework/modules/storage/boltdb/boltdb.go:162:17: cannot use func literal (type func(*"github.com/boltdb/bolt".Tx) error) as type func(*"github.com/coreos/bbolt".Tx) error in argument to db.Bolt.Update
`

**Comment by xiaomaijiang** [comment]
I pull the new code and check my GOPATH,but still has error....  make build can pass but `go run main.go` still has above error

**Comment by xiaomaijiang** [comment]
I find the reason,because in the `framework` project,  `github.com/asdine/storm`  use `cereos/bbolt` but in `boltdb` package, the bolt is `"github.com/boltdb/bolt"`

**Comment by xiaomaijiang** [comment]
I use the 0.10....it work...
