### ISSUE TITLE
admin/task don't work

### ISSUE THREAD

**Issue by haoglehaogle** [infinitbyte/gopa#34]
Hello
When I click tasks in admin, get the following error:

[08-22 10:08:39] [ERR] [elasticsearch.go:174] elastic: Error 404 (Not Found): no such index [type=index_not_found_exception]
2018/08/22 10:08:39 http: panic serving 127.0.0.1:49304: runtime error: invalid memory address or nil pointer dereference
goroutine 7737 [running]:
net/http.(*conn).serve.func1(0xc4200a7680)
	/usr/local/Cellar/go/1.10.3/libexec/src/net/http/server.go:1726 +0xd0
panic(0x48b0860, 0x56511d0)
	/usr/local/Cellar/go/1.10.3/libexec/src/runtime/panic.go:502 +0x229
github.com/infinitbyte/framework/modules/elastic/orm.ElasticORM.GroupBy(0xc420324070, 0x49e1040, 0xc4200a16c0, 0x4a03232, 0x4, 0x4a03232, 0x4, 0x0, 0x0, 0x0, ...)
	/Users/haogle/go/src/github.com/infinitbyte/framework/modules/elastic/orm/elasticsearch.go:179 +0x3fb
github.com/infinitbyte/framework/core/persist.GroupBy(0x49e1040, 0xc4200a16c0, 0x4a03232, 0x4, 0x4a03232, 0x4, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/haogle/go/src/github.com/infinitbyte/framework/core/persist/orm.go:194 +0xbb
github.com/infinitbyte/gopa/model.GetHostStatus(0xffffffffffffffff, 0x14, 0x0, 0x0)
	/Users/haogle/go/src/github.com/infinitbyte/gopa/model/task.go:208 +0x1f6
github.com/infinitbyte/gopa/ui.AdminUI.TasksPageAction(0xc4202e0000, 0x4b8bec0, 0xc420266380, 0xc4201fd500, 0x0, 0x0, 0x0)
	/Users/haogle/go/src/github.com/infinitbyte/gopa/ui/handler.go:28 +0x20d
github.com/infinitbyte/gopa/ui.(AdminUI).TasksPageAction-fm(0x4b8bec0, 0xc420266380, 0xc4201fd500, 0x0, 0x0, 0x0)
	/Users/haogle/go/src/github.com/infinitbyte/gopa/ui/init.go:66 +0x6c
github.com/infinitbyte/framework/core/api.NeedPermission.func1(0x4b8bec0, 0xc420266380, 0xc4201fd500, 0x0, 0x0, 0x0)
	/Users/haogle/go/src/github.com/infinitbyte/framework/core/api/handler.go:272 +0x7c
github.com/infinitbyte/framework/core/api/router.(*Router).ServeHTTP(0xc42030a740, 0x4b8bec0, 0xc420266380, 0xc4201fd500)
	/Users/haogle/go/src/github.com/infinitbyte/framework/core/api/router/router.go:337 +0x741
github.com/gorilla/context.ClearHandler.func1(0x4b8bec0, 0xc420266380, 0xc4201fd500)
	/Users/haogle/git/gopa/vendor/src/github.com/gorilla/context/context.go:141 +0x8b
net/http.HandlerFunc.ServeHTTP(0xc4202fdd80, 0x4b8bec0, 0xc420266380, 0xc4201fd500)
	/usr/local/Cellar/go/1.10.3/libexec/src/net/http/server.go:1947 +0x44
net/http.serverHandler.ServeHTTP(0xc420207e10, 0x4b8bec0, 0xc420266380, 0xc4201fd500)
	/usr/local/Cellar/go/1.10.3/libexec/src/net/http/server.go:2694 +0xbc
net/http.(*conn).serve(0xc4200a7680, 0x4b8ccc0, 0xc4202f2940)
	/usr/local/Cellar/go/1.10.3/libexec/src/net/http/server.go:1830 +0x651
created by net/http.(*Server).Serve

**Comment by medcl** [comment]
fixed, please pull new code.
