### ISSUE TITLE
does it support nofollow tag?

### ISSUE THREAD

**Issue by kenkenchow** [infinitbyte/gopa#40]
I would like to know does it support nofollow tag?

**Comment by medcl** [comment]
not yet, but can be easily to add.

**Comment by kenkenchow** [comment]
Thanks for answering. May I know where/ how to add this feature?

**Comment by medcl** [comment]
check here: https://github.com/infinitbyte/gopa/blob/master/pipeline/joints/filter/parse.go#L114
just process another attribute `rel`, if it is `nofollow` skip it here or mark it .
the `link` will be finally processed and send to further process queue, here:
https://github.com/infinitbyte/gopa/blob/master/pipeline/joints/filter/parse.go#L238
