### ISSUE TITLE
unknown field 'MaxConnsPerHost' in struct literal of type http.Transport

### ISSUE THREAD

**Issue by a-whitej** [infinitbyte/gopa#48]
>lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.10
Release:	18.10
Codename:	cosmic

>go version
go version go1.10.7 linux/amd64

 gopa git:(master) ✗ make
building gopa 0.12.0_SNAPSHOT
framework does not exist
Cloning into 'framework'...
remote: Enumerating objects: 226, done.
remote: Counting objects: 100% (226/226), done.
remote: Compressing objects: 100% (158/158), done.
remote: Total 8626 (delta 117), reused 139 (delta 62), pack-reused 8400
Receiving objects: 100% (8626/8626), 43.81 MiB | 1.29 MiB/s, done.
Resolving deltas: 100% (2175/2175), done.
From https://github.com/infinitbyte/framework
 * branch            master     -> FETCH_HEAD
Already up to date.
From https://github.com/infinitbyte/framework-vendor
 * branch            master     -> FETCH_HEAD
Already up to date.
generate static files
generate main UI pages
update generated info
update configs
/home/user/go/src/github.com/infinitbyte/gopa:/home/user/go/src/github.com/infinitbyte/gopa/vendor:/home/user/go
GOPATH=/home/user/go/src/github.com/infinitbyte/gopa:/home/user/go/src/github.com/infinitbyte/gopa/vendor:/home/user/go CGO_ENABLED=1  GO15VENDOREXPERIMENT="1" go build -ldflags -s -gcflags "-m -m" -o bin/gopa
# github.com/infinitbyte/framework/core/util
../framework/core/util/webhunter.go:385:17: unknown field 'MaxConnsPerHost' in struct literal of type http.Transport

**Comment by chijiao** [comment]
same error

**Comment by chijiao** [comment]
获取最新的软件包源，并添加至当前的apt库
add-apt-repository ppa:longsleep/golang-backports

更新 apt库
apt-get update

安装go
sudo apt-get install golang-go

update go version

**Comment by medcl** [comment]
Upgrade your golang~
